### ISSUE TITLE
Flatpak on Flathub

### ISSUE THREAD

**Issue by JBBgameich** [IJHack/QtPass#637]
Thank you for this nice application :)

In order to make it easier to run on Fedora Kinoite / Silverblue, I'd like to submit it to Flathub.
Flathub requires that app developers agree to their apps being published there, and prefers if upstream developers also maintain the flatpak.

I'd offer to submit and maintain it there, but if you are interested in doing that, that would be even better of course :)

Please let me know if you have any questions about this.

**Comment by annejan** [comment]
I'm very happy with you maintaining it, since I don't use flatpack myself . .

I am already FreeBSD maintainer and some more packages 😉

**Comment by Justinzobel** [comment]
I saw this as I was curious about having this app on Flathub. Hi @jbruechert :D

I looked on Flathub but didn't see it on there, and no PR so I decided to start working on one. It is a bit hacky for now, but it opens, I need to add ssh, but ran out of time.

```
{
    "id": "org.qtpass.qtpass",
    "runtime": "org.kde.Platform",
    "runtime-version": "6.10",
    "sdk": "org.kde.Sdk",
    "command": "qtpass",
    "finish-args": [
        "--device=dri",
        "--share=ipc",
        "--socket=fallback-x11",
        "--socket=wayland",
        "--talk-name=org.kde.StatusNotifierWatcher"
    ],
    "modules": [
        {
            "name": "qtpass",
            "buildsystem": "simple",
            "build-commands": [
                "qmake6 PREFIX=/app",
                "make",
                "make DESTDIR=/app install",
                "install -Dm00644 qtpass.desktop /app/share/applications/org.qtpass.qtpass.desktop",
                "install -Dm00644 artwork/icon.svg /app/share/icons/hicolor/scalable/apps/org.qtpass.qtpass.svg",
                "sed -i 's/qtpass-icon/org.qtpass.qtpass/g' /app/share/applications/org.qtpass.qtpass.desktop"
            ],
            "sources": [
                {
                    "type": "archive",
                    "url": "https://github.com/IJHack/qtpass/archive/v1.7.0.tar.gz",
                    "sha256": "16d7bf01114a7f11c2e361b46e15063f419a27beff54a96985b706da756703c3",
                    "x-checker-data": {
                        "type": "anitya",
                        "project-id": 10288,
                        "stable-only": true,
                        "url-template": "https://github.com/IJHack/qtpass/archive/v${version}.tar.gz"
                    }
                }
            ]
        }
    ]
}
```

**Comment by jbruechert** [comment]
This is the latest state I have got to back then. I don't quite remember how much is working.
I ended up using the pass cli in toolbox "for now" (multiple years).

```yaml
id: org.qtpass.QtPass
runtime: org.kde.Platform
runtime-version: 5.15-22.08
sdk: org.kde.Sdk
command: qtpass
finish-args:
  - --share=ipc
  - --socket=fallback-x11
  - --socket=wayland
  - --device=dri
  - --filesystem=~/.password-store
  - "--filesystem=~/.gnupg:create"
  - "--filesystem=xdg-run/gnupg:ro"
separate-locales: false
base: io.qt.qtwebkit.BaseApp
base-version: 5.15-22.08
branch: stable
rename-appdata-file: qtpass.desktop
rename-desktop-file: qtpass.desktop
rename-icon: qtpass-icon
modules:
  - "git.json"

  - name: pwgen
    buildsystem: autotools
    cleanup:
      - /include
    sources:
      - type: archive
        url: https://github.com/tytso/pwgen/archive/refs/tags/v2.08.tar.gz
        sha256: 8d6e94f28655e61d6126290e3eafad4d17d7fba0d0d354239522a740a270bb2f
      - type: shell
        commands:
          - autoconf
    x-checker-data:
      type: anitya
      project-id: 3738
      stable-only: true
      url-template: https://github.com/tytso/pwgen/archive/refs/tags/v$version.tar.gz

  - name: pass
    buildsystem: simple
    build-commands:
      - make PREFIX=$FLATPAK_DEST install
    sources:
      - type: archive
        url: https://git.zx2c4.com/password-store/snapshot/password-store-1.7.4.tar.xz
        sha256: cfa9faf659f2ed6b38e7a7c3fb43e177d00edbacc6265e6e32215ff40e3793c0
    x-checker-data:
      type: anitya
      project-id: 10071
      stable-only: true
      url-template: https://git.zx2c4.com/password-store/snapshot/password-store-$version.tar.xz

  - name: oathtool
    buildsystem: autotools
    cleanup:
      - /include
    sources:
      - type: archive
        url: https://download.savannah.nongnu.org/releases/oath-toolkit/oath-toolkit-2.6.7.tar.gz
        sha256: 36eddfce8f2f36347fb257dbf878ba0303a2eaafe24eaa071d5cd302261046a9
    x-checker-data:
      type: anitya
      project-id: 2515
      stable-only: true
      url-template: https://download.savannah.nongnu.org/releases/oath-toolkit/oath-toolkit-$version.tar.gz

  - name: pass-otp
    buildsystem: simple
    build-commands:
      - make PREFIX=$FLATPAK_DEST BASHCOMPDIR=$FLATPAK_DEST/etc/bash_completion.d install
    sources:
      - type: archive
        url: https://github.com/tadfisher/pass-otp/releases/download/v1.2.0/pass-otp-1.2.0.tar.gz
        sha256: 5720a649267a240a4f7ba5a6445193481070049c1d08ba38b00d20fc551c3a67
    x-checker-data:
      type: anitya
      project-id: 17240
      stable-only: true
      url-template: https://github.com/tadfisher/pass-otp/releases/download/v$version/pass-otp-$version.tar.gz

  - name: pinentry
    buildsystem: autotools
    config-opts:
      - --disable-pinentry-gtk2
      - --disable-ncurses
      - --disable-fallback-curses
      - --disable-pinentry-curses
      - --disable-pinentry-emacs
      - --disable-pinentry-fltk
      - --disable-pinentry-gnome3
      - --disable-pinentry-tqt
      - --disable-pinentry-tty
      - --enable-pinentry-qt5 # Only enable Qt5 frontend
    sources:
      - type: archive
        url: https://www.gnupg.org/ftp/gcrypt/pinentry/pinentry-1.2.1.tar.bz2
        sha256: 457a185e5a85238fb945a955dc6352ab962dc8b48720b62fc9fa48c7540a4067
    x-checker-data:
      type: anitya
      project-id: 3643
      stable-only: true
      url-template: https://www.gnupg.org/ftp/gcrypt/pinentry/pinentry-$version.tar.bz2

  - name: qtpass
    buildsystem: qmake
    post-install:
      - mkdir -p $FLATPAK_DEST/share/icons/hicolor/512x512/apps
      - mkdir -p /app/share/applications/
      - cp artwork/icon.png $FLATPAK_DEST/share/icons/hicolor/512x512/apps/qtpass-icon.png
      - cp qtpass.desktop $FLATPAK_DEST/share/applications/
      - cp qtpass.appdata.xml $FLATPAK_DEST/share/metainfo/
    sources:
      - type: archive
        url: https://github.com/IJHack/QtPass/archive/refs/tags/v1.3.2.tar.gz
        sha256: 7a68e1afe68462c878c212a79c40ade5ba14b72710c5e62450cf54c7b5621254
      - type: patch
        path: patches/2ca9f0ec5a8d709c97a2433c5cd814040c82d4f3.patch
    x-checker-data:
      type: anitya
      project-id: 10288
      stable-only: true
      url-template: https://github.com/IJHack/QtPass/archive/refs/tags/v$version.tar.gz
```
